# Generated by Django 5.1.1 on 2025-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senderuser',
            name='deposite',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
