# Generated by Django 5.1.5 on 2025-01-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SenderUser',
        ),
    ]
