# Generated by Django 5.1.5 on 2025-01-30 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام زون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='پلیگان')),
            ],
        ),
    ]
