# Generated by Django 5.1.5 on 2025-01-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('in_transit', 'در حال ارسال'), ('delivered', 'تحویل داده شد'), ('canceled', 'کنسل شد')], default='pending', max_length=20)),
                ('package_category', models.CharField(choices=[('other', 'سایر'), ('food', 'غذا'), ('clothes', 'پوشاک'), ('home_devices', 'اساس منزل'), ('electronic_devices', 'لوازم برقی'), ('car_parts', 'قطعات خودرو'), ('cosmetics', 'شوینده و بهداشتی'), ('jewelry', 'زیورآلات'), ('paper', 'کاغذ و مدارک')], default='other', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motor_without_box', 'موتور بدون باکس'), ('motor_with_box', 'موتور باکس دار'), ('sedan', 'سواری بار'), ('light_truck', 'وانت سبک'), ('truck', 'وانت نیسان')], default='motor_without_box', max_length=20)),
                ('package_note', models.TextField(blank=True, null=True)),
                ('source_address', models.TextField()),
                ('source_address_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('source_address_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('destination_user_name', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('destination_address_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.IntegerField(default=0)),
                ('estimated_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_side', models.CharField(choices=[('source_pay', 'پرداخت توسط فرستنده'), ('destination_pay', 'پرداخت توسط گیرنده')], default='source_pay', max_length=20)),
                ('paid_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid_repository', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('wallet', 'پرداخت از کیف پول')], max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('courier_take_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sender.senderuser')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_packages/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='task.task')),
            ],
        ),
    ]
