# Generated by Django 5.1.1 on 2024-09-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EndCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='StartCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vehicle_type', models.CharField(choices=[('motorcycle_no_box', 'Motorcycle Without Box'), ('motorcycle_box', 'Motorcycle With Box'), ('sedan', 'Sedan'), ('light_truck', 'Light Truck'), ('heavy_truck', 'Heavy Truck')], max_length=50)),
                ('payment_type', models.CharField(choices=[('pickup', 'Payment at Pickup'), ('dropoff', 'Payment at Dropoff')], max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('courier_take_time', models.DateTimeField(auto_now_add=True)),
                ('deliverd', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('comment', models.TextField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.courier')),
                ('end_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.endcustomer')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.packagetype')),
                ('start_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.startcustomer')),
            ],
        ),
    ]
