# Generated by Django 5.1.1 on 2024-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='user',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='name',
            field=models.CharField(default='type0', max_length=100),
        ),
    ]
