# Generated by Django 5.1.1 on 2025-01-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_courier_latitude_courier_longitude_courier_status_and_more'),
        ('sender', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='endcustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='end_customer',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='startcustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='start_customer',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('in_transit', 'در حال ارسال'), ('delivered', 'تحویل داده شد'), ('canceled', 'کنسل شد')], default='pending', max_length=20)),
                ('package_catagory', models.CharField(choices=[('other', 'سایر'), ('food', 'غذا'), ('clothes', 'پوشاک'), ('home_devices', 'اساس منزل'), ('electronic_devices', 'لوازم برقی'), ('car_parts', 'قطعات خودرو'), ('cosmetics', 'شوینده و بهداشتی'), ('jwelery', 'زیورآلات'), ('paper', 'کاغذ و مدارک')], default='other', max_length=20)),
                ('source_address', models.TextField()),
                ('vehicle', models.CharField(choices=[('motor_without_box', 'موتور بدون باکس'), ('motor_with_box', 'موتور باکس دار'), ('sedan', 'سواری بار'), ('light_truck', 'وانت سبک'), ('truck', 'وانت')], max_length=20)),
                ('destination_user_name', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_type', models.CharField(blank=True, choices=[('prepay', 'پرداخت در مبدا'), ('postpay', 'پرداخت در مقصد')], max_length=20, null=True)),
                ('payed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('courier_take_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivered', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('sender_note', models.TextField(blank=True, null=True)),
                ('signal_note', models.TextField(blank=True, null=True)),
                ('sender_request_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sender_request_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceuser', to='sender.senderuser')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDeliveryLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='EndCustomer',
        ),
        migrations.DeleteModel(
            name='PackageType',
        ),
        migrations.DeleteModel(
            name='StartCustomer',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
