# Generated by Django 5.1.1 on 2024-09-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_packagetype_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
