# Generated by Django 5.1.1 on 2025-01-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_tasks_courier_remove_endcustomer_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDeliveryLocations',
            new_name='TaskDeliveryLocation',
        ),
    ]
