# Generated by Django 5.1.5 on 2025-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='paid_repository',
            field=models.CharField(blank=True, choices=[('online', 'پرداخت آنلاین'), ('wallet', 'پرداخت از کیف پول')], max_length=20, null=True),
        ),
    ]
