# Generated by Django 5.1.1 on 2024-09-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='courier',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courier',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='star',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle_no_box', 'Motorcycle Without Box'), ('motorcycle_box', 'Motorcycle With Box'), ('sedan', 'Sedan'), ('light_truck', 'Light Truck'), ('heavy_truck', 'Heavy Truck')], default='none', max_length=50),
        ),
    ]
