# Generated by Django 5.1.1 on 2025-01-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_taskdeliverylocations_taskdeliverylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_type',
            field=models.CharField(choices=[('prepay', 'پرداخت در مبدا'), ('postpay', 'پرداخت در مقصد')], default='prepay', max_length=20),
        ),
    ]
