# Generated by Django 5.1.5 on 2025-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_paid_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('delivered', 'تحویل داده شد'), ('canceled', 'کنسل شد')], default='pending', max_length=20),
        ),
    ]
