# Generated by Django 5.1.1 on 2025-01-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('motorcycle_no_box', 'Motorcycle Without Box'), ('motorcycle_box', 'Motorcycle With Box'), ('sedan', 'Sedan'), ('light_truck', 'Light Truck'), ('heavy_truck', 'Heavy Truck')], default='none', max_length=50)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('star', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
