# Generated by Django 5.1.1 on 2025-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('at_work', 'at_work')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_alphabet',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_country_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_first_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_second_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(choices=[('motor_without_box', 'موتور بدون باکس'), ('motor_with_box', 'موتور باکس دار'), ('sedan', 'سواری بار'), ('light_truck', 'وانت سبک'), ('truck', 'وانت')], max_length=20),
        ),
    ]
