# Generated by Django 5.1.1 on 2025-01-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_courierlocations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourierLocations',
            new_name='CourierLocation',
        ),
    ]
